source 'https://github.com/wavesplatform/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'

use_frameworks!(true)

# Pods for CryptoExample
target 'CryptoExample' do

    inherit! :search_paths
    pod 'WavesCrypto'
end
